apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namspace: elk
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch.elk:9200"
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
