apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
  labels:
    app: logstash
spec:
  type: LoadBalancer
  selector:
    app: logstash
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
    protocol: TCP