apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  namespace: elk
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5044
        codec => "json"
      }
    }
    output {
      elasticsearch {
        hosts => "elasticsearch.elk:9200"
        index => "logstash-%{+YYYY.MM.dd}"
        sniffing => false
      }
    }
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false